name: obuddy
description: OBuddy — Calm guidance. Confident parenting.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.25.0
  cloud_firestore: ^4.15.0
  firebase_auth: ^4.17.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
